### PR TITLE
Fixed the updater.

### PR DESCRIPTION
**Pull request by Im-Usif**
Changed the updater URL to https://github.com/SteamRE/SteamKit

### CODE REVIEW

**Comment by luk1337** [comment]
Hm, why is that necessary? The `old` URL seems to work just fine.

**Comment by Weeeishy** [comment]
The protos inthe old URL are not updating I guess? I don't know but I thought they were outdated.

Last commit here was on Jan. https://github.com/SteamDatabase/GameTracking-CSGO/tree/master/Protobufs

**Comment by luk1337** [comment]
They seem to work fine as is.

**Comment by Weeeishy** [comment]
Then thats great!

**Pull request closed without merging**
